name = "sigma-tracker"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "tracker-db"
database_id = "824972ea-ff57-4fcd-8386-1357d73dc82c"

[[r2_buckets]]
binding = "R2"
bucket_name = "tracker-images"
