import Image from 'next/image';
import Link from 'next/link';
import { PricingForm } from './PricingForm';
import styles from './premium-landing.module.css';
import contact from './contact-landing.module.css';

export default function PremiumLanding() {
  return <main className={styles.page}>
    <header className={styles.header}><Link href="/"><Image src="/logo.png" alt="SigmaTracker" width={176} height={41} priority /></Link><nav><a href="#platform">Platform</a><a href="#insights">Insights</a><a href="#pricing">Pricing</a></nav><div><Link href="/login">Log in</Link><a className={styles.button} href="#pricing">Get started</a></div></header>
    <section className={styles.hero}><div className={styles.heroCopy}><p className={styles.kicker}>WORKFORCE INTELLIGENCE</p><h1>Make every working hour <span>visible.</span></h1><p>Time, activity, apps, and screenshots in a single operating system for distributed teams.</p><div className={styles.actions}><a className={styles.button} href="#pricing">Start building your workspace</a><a className={styles.textLink} href="#platform">Explore the platform <b>→</b></a></div><div className={styles.assurance}><span>Built for employee trust</span><span>Configurable privacy</span><span>Live company reporting</span></div></div><HeroProduct /></section>
    <section className={contact.banner}><div><p className={styles.kicker}>HAVE A QUESTION?</p><h2>Talk with the SigmaTracker team.</h2><span>Get product guidance, onboarding help, or a quick answer before you start.</span></div><a className={contact.whatsApp} href="https://wa.me/447882760266" target="_blank" rel="noreferrer">Chat on WhatsApp <b>+44 7882 760266</b></a></section>
    <section className={styles.logoBand}><span>TIME TRACKING</span><span>ACTIVITY INSIGHTS</span><span>APP INTELLIGENCE</span><span>TEAM REPORTING</span><span>SCREENSHOTS</span></section>
    <section id="platform" className={styles.platform}><div className={styles.sectionHead}><p className={styles.kicker}>ONE COMPLETE PICTURE</p><h2>Stop guessing how work is moving.</h2><p>SigmaTracker turns daily work into clear, helpful signals for managers and teams.</p></div><div className={styles.cards}><article><b>01</b><h3>Time that tells the truth</h3><p>Live timers and accurate timesheets show the shape of every workday.</p></article><article><b>02</b><h3>Activity with context</h3><p>Measured averages help identify focus without reacting to a single quiet minute.</p></article><article><b>03</b><h3>Visibility you control</h3><p>Set screenshot intervals, idle policies, retention, and access for each workspace.</p></article></div></section>
    <section id="insights" className={styles.insights}><div className={styles.insightVisual}><span className={styles.dot}/><div className={styles.insightCard}><p>WEEKLY FOCUS SCORE</p><strong>84<span>%</span></strong><small>+8.4% from last week</small><div className={styles.line}><i/><i/><i/><i/><i/><i/><i/></div></div></div><div className={styles.insightCopy}><p className={styles.kicker}>INSIGHTS, NOT SURVEILLANCE</p><h2>Turn activity into better team conversations.</h2><p>See patterns across time, applications, and attendance. Keep the conversation focused on outcomes and support, not surveillance.</p><ul><li>Hourly and daily activity trends</li><li>Top applications by real usage</li><li>Employee and company reporting</li></ul></div></section>
    <section className={styles.workflow}><div className={styles.sectionHead}><p className={styles.kicker}>READY IN MINUTES</p><h2>A simple launch sequence.</h2></div><div className={styles.steps}><article><span>01</span><h3>Set up your workspace</h3><p>Choose your team size and create the company hub.</p></article><article><span>02</span><h3>Invite your team</h3><p>Give employees their secure account and desktop access.</p></article><article><span>03</span><h3>See the signal</h3><p>Review trustworthy data in the dashboard as work happens.</p></article></div></section>
    <section className={styles.desktop}><div><p className={styles.kicker}>NATIVE WINDOWS APP</p><h2>Designed for the actual workday.</h2><p>Start, pause, and review from a desktop tracker that stays light and in sync.</p><a className={styles.button} href="/SigmaTracker.msi" download="SigmaTracker.msi">Download for Windows</a></div><div className={styles.appCard}><Image src="/app-icon.png" alt="SigmaTracker desktop app" width={88} height={88}/><div><b>SigmaTracker Desktop</b><span>Securely connected to your workspace</span><em>Windows installer</em></div></div></section>
    <section id="pricing" className={styles.pricing}><div className={styles.sectionHead}><p className={styles.kicker}>STRAIGHTFORWARD PRICING</p><h2>One plan. Clear value.</h2><p>$1 per employee per month. No complicated tiers.</p></div><PricingForm /></section>
    <section className={contact.talk}><p className={styles.kicker}>TALK WITH US</p><h2>Need help choosing the right setup?</h2><p>Our team is ready to help you get SigmaTracker working for your company.</p><a className={contact.whatsApp} href="https://wa.me/447882760266" target="_blank" rel="noreferrer">Chat on WhatsApp <b>+44 7882 760266</b></a></section>
    <footer><Image src="/logo.png" alt="SigmaTracker" width={160} height={37}/><span>Clearer workdays start here.</span><span>Copyright {new Date().getFullYear()} SigmaTracker</span></footer>
  </main>;
}
function HeroProduct(){return <div className={styles.product}><div className={styles.productTop}><span><Image src="/app-icon.png" alt="" width={20} height={20}/> SigmaTracker</span><i>● ● ●</i></div><div className={styles.productGrid}><aside><b>ST</b><span className={styles.selected}>Overview</span><span>Timesheets</span><span>Screenshots</span><span>Reports</span></aside><div className={styles.productMain}><div className={styles.productTitle}><div><small>WORKSPACE OVERVIEW</small><h3>Today&apos;s momentum</h3></div><em>Live</em></div><div className={styles.stats}><div><small>TIME LOGGED</small><strong>07:18:42</strong><i>+14% today</i></div><div><small>TEAM ACTIVITY</small><strong>84%</strong><i>Healthy focus</i></div></div><div className={styles.barCard}><b>Productive time by hour</b><div>{[28,44,35,74,62,89,78,93,67].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></div><div className={styles.members}><p><span>AM</span>Alex Morgan <b>92%</b></p><p><span>RW</span>Riley Wong <b>86%</b></p></div></div></div></div>}
